### PR TITLE
Resume Builder

### PR DESCRIPTION
**Pull request by POONAMJADHAV63**
I have Created Simple Resume Builder website with the use of HTML, CSS, JavaScript, Typescript. I have followed all the requirements that need to build an interactive Resume Builder. In this website we have to fill all the details that is required to Proceed  and after that We have to Print our Resume. In README.md I have uploaded all the Screenshots from start to end for better clarity.

### CODE REVIEW

**Comment by POONAMJADHAV65** [comment]
I have Created Simple Resume Builder website with the use of HTML, CSS, JavaScript, Typescript.

**Comment by panditamey** [comment]
Merged but improved ui ! use tailwind and add more and descriptive commits rather than single commit

**Comment by panditamey** [comment]
hey 
Kindly port Static HTML to React Components

**Comment by panditamey** [comment]
Also we have removed "By POONAM JADHAV 😊" as this is open source project , from next onwards don’t add any personal things in site

**Comment by POONAMJADHAV63** [comment]
Okk👍

**Pull request merged**
